import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient, Prisma } from './generated/prisma/client.js';

export interface CreatePrismaClientOptions {
  /**
   * The pooled connection string (DATABASE_URL, port 6543).
   */
  connectionString: string;

  log?: boolean;
}

export function createPrismaClient({
  connectionString,
  log = false,
}: CreatePrismaClientOptions): PrismaClient {
  const adapter = new PrismaPg({
    connectionString,
  });

  return new PrismaClient({
    adapter,
    log: log ? ['warn', 'error'] : ['error'],
  });
}

export { PrismaClient };

/**
 * Prisma client available inside a `$transaction` callback.
 *
 * This type is generated by Prisma and should be preferred over
 * manually omitting connection-level methods from PrismaClient.
 */
export type PrismaTransactionClient = Prisma.TransactionClient;
