import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient, Prisma } from './generated/prisma/client.js';

export interface CreatePrismaClientOptions {
  /**
   * The pooled connection string (DATABASE_URL, port 6543).
   */
  connectionString: string;

  log?: boolean;
}

export function createPrismaClient({
  connectionString,
  log = false,
}: CreatePrismaClientOptions): PrismaClient {
  const adapter = new PrismaPg({
    connectionString,
  });

  return new PrismaClient({
    adapter,
    log: log ? ['warn', 'error'] : ['error'],
  });
}

export { PrismaClient };

/**
 * Prisma client available inside a `$transaction` callback.
 *
 * This type is generated by Prisma and should be preferred over
 * manually omitting connection-level methods from PrismaClient.
 */
export type PrismaTransactionClient = Prisma.TransactionClient;

/**
 * A value Prisma will accept in a Json column.
 *
 * Exported because `Record<string, unknown>` is not one, and rightly: unknown
 * could be a Date or a function, neither of which survives being stored as
 * JSON. Typing audit payloads with this makes the compiler prove they are
 * storable, instead of the database discovering they are not.
 */
export type InputJsonValue = Prisma.InputJsonValue;
